# Generated by Django 5.2 on 2025-04-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_use_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='use_persona',
        ),
    ]
