# Generated by Django 5.2 on 2025-04-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatsession_use_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='use_persona',
            field=models.BooleanField(default=False),
        ),
    ]
