# Generated by Django 5.2 on 2025-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_use_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='selected_model',
            field=models.CharField(blank=True, default='gemma3:1b', max_length=255, null=True),
        ),
    ]
